### ISSUE TITLE
i may have broken http://phpimagick.com/

### ISSUE THREAD

**Issue by MadVillager** [Danack/Imagick-demos#31]
was playing around with the whirlygif demo and now every page at phpimagick.com has an error message on it !

( 4 me at least ! )

Exception Predis\Connection\ConnectionException: 'Connection refused [tcp://127.0.0.1:6379]'

etc.

**Comment by Danack** [comment]
...thanks. I've poked the redis instance to make it start up again.

I really need to find out why redis keeps falling over. Hmm.

It might be because the server was out of diskspace.....I've made a load of space to see if that 'fixes' it. At some point I'm going to redeploy the whole site using containers, which should make most of this problem 'go away'.

Please give me another shout if you see this again.

**Comment by MadVillager** [comment]
thanx mate

fyi i'm still seeing some busted pages

errors thrown:

Exception Jig\JigException: 'Failed to render template 'Jig\CompiledTemplate\exampleJig' : Connection refused [tcp://127.0.0.1:6379]'

http://phpimagick.com/ImagickPixel/setColor

as well as

502 Bad Gateway

http://phpimagick.com/ImagickPixel/getColorCount

as well as

Exception Predis\Connection\ConnectionException: 'Connection refused [tcp://127.0.0.1:6379]'

http://phpimagick.com/ImagickPixelIterator

**Comment by Danack** [comment]
Thanks. So it’s the redis cache that keeps falling over, but somewhat ironically I won’t be able to restart it until tomorrow morning evening as i’m away from a computer as i’m attending a redis conference...

**Comment by Danack** [comment]
It's back again - possibly it was just running out of memory. I will be moving it to a container based deployment soon, so will just keep kicking it when it falls over rather than fixing it properly until it's in a container.
