### ISSUE TITLE
getImageMatte() method is deprecated what is replacement to use ?

### ISSUE THREAD

**Issue by skdevelopers** [Danack/Imagick-demos#41]
Reported from Imagick::getImageMatte() method is deprecated in Imagick new version and please told me what we use in replacement

**Comment by skdevelopers** [comment]
Any Answer ? no one face this issue ?

**Comment by Sublan** [comment]
I'm using old version of Imagick >>::

**Comment by Danack** [comment]
Probably  Imagick::getImageAlphaChannel https://www.php.net/manual/en/imagick.getimagealphachannel

ImageMagick changed from using 'matte' to 'opacity' and that's why the old one is deprecated. But it's fine to keep using it until you plan to upgrade to a version of imagemagick that doesn't support it.
