### ISSUE TITLE
PHP Warning: Version warning: Imagick was compiled against Image Magick version 1654 but version 1650 is loaded

### ISSUE THREAD

**Issue by lgdelai** [Danack/Imagick-demos#45]
Hello everyone.

In my hosting at **Hostgator** I am receiving this error without stopping in the "**error_log**" file.

The file "**error_log**" containing this message appears on several random pages.

In addition, I receive the following message **every hour**, in the standard cpanel email:
**Title:** 
**Cron <delaio86 @ srv100> / usr / bin / php -f /home2/delaio86/public_html/utilidadeninja.com/site/wp-cron.php> / dev / null**
**Content:**
```
PHP Warning: Module 'imagick' already loaded in Unknown on line 0
PHP Warning: Version warning: Imagick was compiled against Image Magick version 1654 but version 1650 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
```
In contact with the Hosting, I was informed that this is an incompatibility of Imagick with versions **73 and 74 of PHP**.

The attendant then said that he could not do anything because it is a shared hosting and suggested that I use an outdated version "**72**" of php.

**I said that I would not use an outdated version, for obvious reasons.**

I would like your help to try to stop generating these messages in the log for all my folders without having to outdate my PHP.

I often have to look for the files and delete them one by one, as they never stop growing.

I already tried to insert a **.user.ini** file containing the line:
`imagick.skip_version_check = true`
And a **php.ini** file with the line:
`extension = imagick.so`

Both, in the root folder of the hosting, the errors continue to appear randomly.

Thanks in advance to anyone who can help.

**Comment by Danack** [comment]
Fair warning, I doubt I'm going to be able to resolve your problem, but may be able to give some info.

> I was informed that this is an incompatibility of Imagick with versions 73 and 74 of PHP.

No, it's testing that the version of the ImageMagick loaded is the one that Imagick was compiled against. This can happen when someone upgrades one of them, but not the other.

However the Imagick and ImageMagick libraries were installed, they should probably be installed again to get the versions to match.

> I already tried to insert a .user.ini file containing the line:

Yeah, that won't work. The check is done before user ini files are loaded due to the way PHP + extensions work internally.

fyi, I don't think people should be using shared hosting and particularly not for Imagick

Digital Ocean VPS start at $5 a month. https://www.digitalocean.com/pricing/ or maybe a dedicated wordpress hosting company would be better for you: https://wordpress.org/hosting/

Closing as this is not a problem I can resolve.
